#!/usr/bin/env bash
# Tangle org files using Emacs

# Default to all org files excluding those with | suffix
[ $# -eq 0 ] && set -- *[!\|].org

# Tangle files using Emacs batch mode
emacs --batch \
  --eval "(require 'org)" \
  --eval "(setq org-confirm-babel-evaluate nil)" \
  --eval "(dolist (file command-line-args-left)
            (message \"Tangling %s...\" file)
            (with-current-buffer (find-file-noselect file)
              (org-babel-tangle)))" \
  -- "$@"

